
# Configuration for Communication with datalogic scanner
scanner:
  com_port: ttyACM0
  baudrate: 9600
  timeout: 1

# Configuration for database location
database:
  path: /home/daniel/Shared/scanned_cabinet.db
