
# Configuration for Communication with datalogic scanner
scanner:
  com_port: COM3
  baudrate: 9600
  timeout: 1

# Configuration for database location
database:
  path: D:\Repository\CabinetScanner\database.db
